### ISSUE TITLE
npm test fails

### ISSUE THREAD

**Issue by abdennour** [alexcasalboni/serverless-multi-region-client-demo#1]
Great Formula for DDB cost increase. 

Anyway, I assume your boilerplate is create-react-app. However, "npm test" does not work.

```

> serverless-multi-region-client-demoÉ1.0.0 test /private/tmp/serverless-multi-region-client-demo
> react-scripts test --env=jsdom

2018-01-30T21:39:16,043: Ä0x7fffceffd3c0Å the owner of /usr/local/var/run/watchman/abdennour-state is uid 0 and doesn't match your euid 501

Watchman:  watchman --no-pretty get-sockname returned with exit code=1, signal=null, stderr= 2018-01-30T21:39:16,043: Ä0x7fffceffd3c0Å the owner of /usr/local/var/run/watchman/abdennour-state is uid 0 and doesn't match your euid 501

jest-haste-map: Watchman crawl failed. Retrying once with node crawler.
  Usually this happens when watchman isn't running. Create an empty é.watchmanconfigé file in your project's root folder or initialize a git or hg repository in your project.
  Error: watchman --no-pretty get-sockname returned with exit code=1, signal=null, stderr= 2018-01-30T21:39:16,043: Ä0x7fffceffd3c0Å the owner of /usr/local/var/run/watchman/abdennour-state is uid 0 and doesn't match your euid 501

2018-01-30T21:39:16,560: Ä0x7fffceffd3c0Å the owner of /usr/local/var/run/watchman/abdennour-state is uid 0 and doesn't match your euid 501

Watchman:  watchman --no-pretty get-sockname returned with exit code=1, signal=null, stderr= 2018-01-30T21:39:16,560: Ä0x7fffceffd3c0Å the owner of /usr/local/var/run/watchman/abdennour-state is uid 0 and doesn't match your euid 501

events.js:182
      throw er; // Unhandled 'error' event
      Ü

Error: watchman --no-pretty get-sockname returned with exit code=1, signal=null, stderr= 2018-01-30T21:39:16,560: Ä0x7fffceffd3c0Å the owner of /usr/local/var/run/watchman/abdennour-state is uid 0 and doesn't match your euid 501

    at ChildProcess.<anonymous> (/private/tmp/serverless-multi-region-client-demo/node_modules/sane/node_modules/fb-watchman/index.js:198:18)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm ERR! Test failed.  See above for more details
```

**Comment by alexcasalboni** [comment]
Hi @abdennour, I have just re-cloned the repo, `npm install`, and `npm test`.
Everything works fine here.

I guess something's wrong with your npm. It looks like [this](https://github.com/facebook/react-native/issues/2941) might help. You probably have different versions of `watchman` installed via npm and brew.
